### ISSUE TITLE
Regression with bGURLS

### ISSUE THREAD

**Issue by AzothAmmo** [LCSL/GURLS#8]
I'm working on a problem where I need to perform regression on a very large dataset.  From looking at bGURLS, it seems like it is currently designed to only perform classification, although GURLS can handle both.

Is it possible to modify bGURLS to perform regression?  I've started looking into this but want to make sure it isn't fundamentally impossible given some design considerations that I don't know about.

**Comment by vvasco** [comment]
I'm trying to use bGurls for regression on a large dataset. I prepare my data using the function bigTrainTestPrepare, but this gives an error, because it is designed for classification. 
Specifically, the error I get is at line 88:

codes = 2*eye(T) - 1;

as T (the number of classes) is a real number in my case.

Is there another function that I might use to prepare the data for regression or should I modify the bigTrainTestPrepare function?
